## Deploy Azure Resource using bicep

name: Azure Deployment

on:
    workflow_dispatch:

    push:
        branches:
            - main

permissions:
    id-token: write
    contents: read

env:
    azCliVersion: 2.30.0
    environment: 'AzureDemoEnv'
            
jobs:
    # Validate and Plan the deployment
    validateDeployment:
        runs-on: ubuntu-latest
        
        steps:
          
            - uses: actions/checkout@main
              name: Checkout

            - uses: azure/login@v1
              name: Azure Login
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - uses: azure/cli@v1
              name: validateTemplates
              with:
                inlineScript: |
                    az deployment sub validate --location westeurope --template-file ./azDeployment.bicep

            - uses: azure/cli@v1
              name: planDeployment
              with:
                inlineScript: |
                    az deployment sub create --location westeurope --template-file ./azDeployment.bicep --what-if --verbose

    # Deploy the resources
    deployResources:
        runs-on: ubuntu-latest
        environment: $environment
        needs: [
          validateDeployment
        ]
        
        steps:
            - uses: actions/checkout@main
              name: Checkout

            - uses: azure/login@v1
              name: Azure Login
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            # Deploy Bicep file
            - name: deploy
              uses: azure/arm-deploy@v1
              with:
                scope: 'subscription'
                template: ./azDeployment.bicep
              # parameters: 'storagePrefix=mystore storageSKU=Standard_LRS'
                failOnStdErr: false
