## Deploy Azure Resource using bicep

name: Azure Deployment

on:
    workflow_dispatch:

    push:
        branches:
            - main

permissions:
    id-token: write
    contents: read

env:
    azCliVersion: 2.30.0
    environment: 'AzureDemoEnv'
    region: 'westus'
            
jobs:
    # Validate and Plan the deployment
    validateDeployment:
        runs-on: ubuntu-latest
        
        steps:
          
            - uses: actions/checkout@main
              name: Checkout

            - uses: azure/login@v1
              name: Azure Login
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            # Deploy Bicep file
            - name: validateTemplates
              uses: azure/arm-deploy@v1
              with:
                scope: 'subscription'
                template: ./azDeployment.bicep
                failOnStdErr: false
                deploymentMode: 'Validate'
                region: ${{ env.region }}

            - name: planDeployment
              uses: azure/arm-deploy@v1
              with:
                scope: 'subscription'
                template: ./azDeployment.bicep
                failOnStdErr: false
                additionalArguments: "--what-if"
                region: ${{ env.region }}

    # Deploy the resources
    deployResources:
        runs-on: ubuntu-latest
        environment: ${{ vars.environment}}
        needs: [
          validateDeployment
        ]
        
        steps:
            - uses: actions/checkout@main
              name: Checkout

            - uses: azure/login@v1
              name: Azure Login
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            # Deploy Bicep file
            - name: deploy
              uses: azure/arm-deploy@v1
              with:
                scope: 'subscription'
                template: ./azDeployment.bicep
              # parameters: 'storagePrefix=mystore storageSKU=Standard_LRS'
                failOnStdErr: false
                region: ${{ env.region }}
