## deploy azDeploySecureSub.bicep

name: REDCap Unzip Test

on:
    workflow_dispatch:

    push:
        branches:
            - main

permissions:
    id-token: write
    contents: read

env:
    azCliVersion: 2.30.0
    environment: 'env-redcap'
    region: 'eastus'

jobs:
    # Validate the Bicep templates
    redcap-unzip-test:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@main
            name: Checkout

          - name: installPrereqs
            run: | 
                sudo apt-get install unzip -y && sudo apt-get install -y python3 python3-pip
        
          - name: pwd & ls
            run: | 
                pwd
                ls
        
          - name: runScript
            run: | 
                ./deploy.sh

          - uses: montudor/action-zip@v1
            with:
                args: unzip -qq redcap.zip -d redcap
          
          - name: pwd & ls
            run: | 
                pwd
                ls