## deploy azDeploySecureSub.bicep

name: REDCap Unzip Test

on:
    workflow_dispatch:

    push:
        branches:
            - main

permissions:
    id-token: write
    contents: read

env:
    azCliVersion: 2.30.0
    environment: 'env-redcap'
    region: 'eastus'
    redcap: 'https://strgredcapext.blob.core.windows.net/redcao/redcap13.8.5.zip?sp=r&st=2023-09-29T14:31:44Z&se=2023-09-29T22:31:44Z&spr=https&sv=2022-11-02&sr=b&sig=CKhjqTNyWYlsSicPYZJcha%2F6v5xcrFSQO70237tO%2BEY%3D'

jobs:
    # Validate the Bicep templates
    redcap-unzip-test:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@main
            name: Checkout

          - name: installPrereqs
            run: | 
                sudo apt-get install unzip -y && sudo apt-get install -y python3 python3-pip
        
          - name: listDir01
            run: ls
        
          - name: downloadRedcap
            run: deploy.sh
          
          - name: runScript
            run: |
              echo "Unzipping REDCap"  
              unzip -qq redcap.zip -d redcap
          
          - name: listDir03
            run: ls